### ISSUE TITLE
[Suggestion] Separate Slade from Laravel, then create another package that implements the Service Provider

### ISSUE THREAD

**Issue by lancepioch** [Evertt/Slade#11]
I'd imagine it'd look somewhat like this: https://github.com/rcrowe/TwigBridge/tree/0.7
but minus a bunch of that because it's being developed with Laravel in mind.

I just think it'd be neat to be able to use this in other frameworks other than Laravel/Lumen.

**Comment by Evertt** [comment]
I agree, I'll get on it within a few days.

**Comment by Evertt** [comment]
Okay I've made it Laravel independent, but I'm doubting wether to make a completely separate package for the bridge. The reason is because the "bridge" is really only one file, the ServiceProvider. I find it a bit of a waste to create a whole separate package for only one tiny file.

**Comment by lancepioch** [comment]
I think since it's just the one SP file, it's fine. Especially since it's built with Laravel in mind.

**Comment by Evertt** [comment]
Evert van Brussel wants you to join a Meetup

"Hey there!

Have you ever wondered if your relationships with your friends, family and/or partner could be easier than it is right now? or be more meaningful? or more loving? The past 5 years I've been learning a skill that has helped me to make my relationships more meaningful, more loving and easier than ever.

And now I'm very excited about teaching others how to get the same experience! Have I made you curious? Then join the next meetup so I can show you what it's all about!

Cheers,

Evert"

--------------------------------------

Amsterdam Nonviolent Communication Practice Group

This is an open practice group for practicing nonviolent communication. I, Evert van Brussel, will be leading the evenings. I have 5 years of experience in NVC and I'm very passionate about suppor...

Join now!
http://www.meetup.com/Amsterdam-Nonviolent-Communication-Practice-Group/t/ti1_1/?gj=ej4

--------------------------------------

If you're not interested, there's no need to do anything. Meetup will not keep your address on any list.
