### ISSUE TITLE
PHP 5.5 Support

### ISSUE THREAD

**Issue by lancepioch** [Evertt/Slade#3]
It's a little restrictive when your library can only be used by ~1% of PHP users.

The new features in PHP 5.6 are:
- Constant expressions
- Variadic functions via ...
- Argument unpacking via ...
- Exponentiation via **
- use function and use const

While I agree it's nice to be able to use these shortcuts and you should always upgrade your version, I think it'd be better to replace those for now because this seems like a really good library.

Would you be open to a PR for this?

**Comment by Evertt** [comment]
Yes I certainly would
