### ISSUE TITLE
Windows Compatability

### ISSUE THREAD

**Issue by lancepioch** [Evertt/Slade#5]
Windows 8.1 (Version 6.3 (Build 9600))
PHP 5.5.12

```
$ phpspec run
Slade\Nodes\CommentNode
  26  - it parses an html comment block
...". expected "<!--  ...", but got "<!--

Slade\Nodes\IfNode
  25  - it parses insides if provided with a truthy
' in \Slade\src\Parser.php line 128'

Slade\Nodes\UnlessNode
  25  - it parses insides if provided with a falsy
' in \Slade\src\Parser.php line 128'

Slade\Nodes\YieldNode
  25  - it should parse default content if a section does not exist
' in \Slade\src\Parser.php line 128'

/  skipped: 0%  /  pending: 0%  /  passed: 89%  /  failed: 2%   /  broken: 8%   /  37 examples
16 specs
37 examples (33 passed, 1 failed, 3 broken)
127ms
```

I was able to fix the failed test by replacing "\n" with PHP_EOL. I feel like these errors have to do with the fact that on Linux `PHP_EOL === "\n"` and on Windows `PHP_EOL === "\r\n"`.

**Comment by Evertt** [comment]
Ah right, you are correct. I forgot about using PHP_EOL in my tests.
Right now I'm refactoring a different part of my code, so in case you want to make a PR that would be cool. If not then I'll do it myself after I've finished the refactoring I'm working on now.
