### ISSUE TITLE
Better names for the different classes

### ISSUE THREAD

**Issue by Evertt** [Evertt/Slade#8]
I found it hard to think of clear descriptive names for the classes I was writing. And now I'm not very satisfied with them.

I have a TemplateBlock class which represents a block of Slade template. So that means it holds 1 line plus all of its indented children. And then I call all of the different kinds of code-blocks Nodes, like the ForeachNode and the IfNode etc. However, I don't think the word Node clearly conveys what it is or does. Also to me Node kind of sounds similar to Block, so it's hard to guess the distinction just by reading the names.

Would anyone like to help me with this? Does anyone have a suggestion for better names?

**Comment by lancepioch** [comment]
I'd say that [Twig](http://github.com/twigphp/Twig) has a sufficient naming scheme and layout that could be roughly mimicked.

**Comment by Evertt** [comment]
That library is huge. I'm sure they did it like that, because it's the cleanest and least-error-prone way to do it. Right now I don't want to spend that much time on understanding how that whole thing works.
