### ISSUE TITLE
Compile templates for improving performance

### ISSUE THREAD

**Issue by Evertt** [Evertt/Slade#9]
Right now all templates are parsed every single time they are used, which will probably lead to performance issues in the future.

I saw that laravel-blade compiles them and then reuses that compiled template. I would also like to implement this, but I'm not quite sure yet how to do that.

So I'm posting it here just to remind myself and also to ask if anyone feels excited to help me. :-)

**Comment by Evertt** [comment]
@lancepioch, @warrenca, @bhargavjoshi, @xLink

I'm tagging you guys just to make sure somebody sees this. Would any of you like to help me with this?

**Comment by bhargavjoshi** [comment]
@Evertt sure lets do this :smile:
Lets hack this in the weekend.

**Comment by lancepioch** [comment]
How similarly do we want it to function? Here's a start: https://github.com/laravel/framework/blob/5.0/src/Illuminate/View/Compilers/BladeCompiler.php

**Comment by Evertt** [comment]
@bhargavjoshi This weekend I don't have time, but I'll try to make a start before the weekend. Then if you like the way I started things you could continue it as far as you like and I'll continue it after the weekend again.

@lancepioch yes that's where I'm getting my inspiration from indeed. I will try to make it somewhat similar.

I feel so excited that people want to contribute to my very first open-source package. :-D

**Comment by lancepioch** [comment]
@Evertt I first learned about Slim when using codepen.io and I really enjoyed the syntax, very clean, easy, and non cluttered. I was a little disheartened to see that there wasn't any PHP support and that it was Ruby only. I'd really love to be able to use this package for all my new template files.

I think it'd be a good idea to try to line up this syntax and incorporate some of the core tests from the original Ruby package: https://github.com/slim-template/slim/tree/master/test/core - although this is just my opinion.

**Comment by Evertt** [comment]
@lancepioch I chose a slightly different syntax on purpose, because of my personal preferences and I'm inclined to keep it like this for now. Though you can fork it and change the syntax if you like of course.

Here's a few of the changes I made and why.
On the [slim-lang website](http://slim-lang.com) you see that they have control code syntax like this:

``` slim
- unless items.empty?
```

which I was kinda okay with, but then I found out they have a logicless mode as well, like this:

``` slim
- article
```

Which basically means `if ( ! empty( $article ) )` and I love that syntax, short and sweet. But what I didn't like about it was that a dash for me doesn't make clear it should be a conditional. And when I saw ruby slim use `-! article` for the inverted conditional, I thought, why not just use a question-mark for a conditional and an exclamation-mark for an inverted conditional? It looks much more intuitive for me when I see `? article` and `! article`. Finally I needed something for an iterable. Logic-less ruby slim uses the same syntax for an iterable as it does for a conditional, but I want to keep that sort-of separate. So I use `> articles` for an iterable. Of course, if the iterable returns a falsy then it still won't try to iterate.

Also I like how my `> articles` is equal to:

``` slim
- for article in articles do
```

Mine is very short and sweet, don't you think? I'm thinking of giving the developer the option of choosing their own variable-name for the individual items (instead of the plural->singular conversion that slade does by default). That syntax would then look something like this:

```
> articles > item
```

What do you think about that? :-)
Now I can understand you'd like to keep the original syntax, because plugins already exist and maybe you don't want to learn a new syntax again. I just like improving things when I see room for improvement.

**Comment by Evertt** [comment]
This is done. Go see the changes if you want.
